version: 0.2
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://daily-horoscope-project-qgarcia/
      #It copies all of the contents of the build folder to the S3 bucket we setup and enables public access on all files copied over.
artifacts:
  files:
    - "build/*"
    - "build/**/*"
